[versions]
paper = "1.19.4-R0.1-SNAPSHOT"
shadow = "8.3.2"
bukkitgradle = "0.10.1"
sqlite = "3.46.1.3"
lombok = "1.18.34"
paperweight = "1.7.3"
ormlite = "6.1"
jetbrains-annotations = "26.0.0"

[libraries]
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
ormlite = { module = "com.j256.ormlite:ormlite-jdbc", version.ref = "ormlite" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
bukkitgradle = { id = "ru.endlesscode.bukkitgradle", version.ref = "bukkitgradle" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
